title: Ultimate Dogma


markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    cdn: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"


#theme: minima
remote_theme: jekyll/minima@main

plugins:
  - jekyll-remote-theme            # plugin is whitelisted on GH Pages
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

minima:
  skin: dark

header_pages:
  - index.md
  - content.md

show_excerpts: true
